# Generated by Django 5.2.3 on 2025-06-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioAbertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(help_text='Formato: MM/AAAA', max_length=6, verbose_name='Mês/Ano Referência')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('F', 'Fechado')], default='A', max_length=1, verbose_name='Status')),
                ('data_abertura', models.DateField(verbose_name='Data de Abertura')),
                ('data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
            ],
            options={
                'verbose_name': 'Abertura de Convênio',
                'verbose_name_plural': 'Aberturas de Convênios',
                'ordering': ['-mes_referencia', 'data_abertura'],
            },
        ),
    ]
