# Generated by Django 5.2.3 on 2025-06-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_convenioabertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenioabertura',
            name='mes_referencia',
            field=models.CharField(help_text='Formato: MM/AAAA', max_length=7, verbose_name='Mês/Ano Referência'),
        ),
    ]
