# Generated by Django 5.2.3 on 2025-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_convenioabertura_mes_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_loja', models.IntegerField(blank=True, null=True, verbose_name='Código da Loja')),
                ('nome_convenio', models.CharField(help_text='Nome de identificação do convênio.', max_length=100, verbose_name='Nome do Convênio')),
                ('cnpj', models.CharField(help_text='CNPJ do conveniado. Formato: XX.XXX.XXX/XXXX-XX', max_length=18, unique=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa de Contato')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail de Contato')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Contato')),
                ('ativo', models.BooleanField(default=True, help_text='Indica se o convênio está ativo.', verbose_name='Ativo')),
                ('qtd_parc_permi', models.IntegerField(default=1, help_text='Quantidade máxima de parcelas permitidas para este convênio.', verbose_name='Parcelas Permitidas')),
                ('cod_evento', models.CharField(blank=True, help_text='Código de evento relacionado para integração.', max_length=20, null=True, verbose_name='Código do Evento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='convenios/logos/', verbose_name='Logo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Convênio',
                'verbose_name_plural': 'Convênios',
                'ordering': ['nome_convenio'],
            },
        ),
    ]
