# Generated by Django 5.2.3 on 2025-06-26 01:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_convenio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenioEmissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14, verbose_name='CPF do Cliente')),
                ('SALDO', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo do Cliente')),
                ('MES_REFERENCIA', models.CharField(help_text='Mês e ano de referência (ex: 202312)', max_length=6, verbose_name='Mês de Referência')),
                ('QTD_PARCELA', models.IntegerField(verbose_name='Quantidade de Parcelas')),
                ('VALOR', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total da Transação')),
                ('DATA_TRANSACAO', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Transação')),
                ('HORA_TRANSACAO', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora da Transação')),
                ('ID_CLIENTE', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissoes_convenio', to='core.cliente', verbose_name='ID do Cliente')),
                ('ID_CONVENIO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emissoes', to='core.convenio', verbose_name='ID do Convênio')),
            ],
            options={
                'verbose_name': 'Emissão de Convênio',
                'verbose_name_plural': 'Emissões de Convênios',
                'db_table': 'CONVENIO_EMISSAO',
                'ordering': ['-DATA_TRANSACAO', '-HORA_TRANSACAO'],
            },
        ),
        migrations.CreateModel(
            name='ConvenioEmiDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_PARCELA', models.IntegerField(verbose_name='Número da Parcela')),
                ('DATA_EMISSAO', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data e Hora da Emissão')),
                ('DATA_VENCIMENTO', models.DateField(verbose_name='Data de Vencimento')),
                ('STATUS_PG', models.CharField(choices=[('A', 'Aberto'), ('P', 'Pago'), ('C', 'Cancelado')], default='A', max_length=20, verbose_name='Status do Pagamento')),
                ('VALOR_PARCELA', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Parcela')),
                ('ID_CONVENIO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes_emissao', to='core.convenio', verbose_name='ID do Convênio')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='core.convenioemissao', verbose_name='ID da Emissão')),
            ],
            options={
                'verbose_name': 'Detalhe da Emissão de Convênio',
                'verbose_name_plural': 'Detalhes da Emissão de Convênio',
                'db_table': 'CONVENIO_EMI_DET',
                'ordering': ['ID__pk', 'N_PARCELA'],
                'unique_together': {('ID', 'N_PARCELA')},
            },
        ),
    ]
