# Generated by Django 5.2.3 on 2025-07-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convenioemissao_convenioemidet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenioemissao',
            name='MES_REFERENCIA',
            field=models.CharField(help_text='Mês e ano de referência (ex: 122023)', max_length=7, verbose_name='Mês de Referência'),
        ),
    ]
